/// Flutter icons CutsomIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CutsomIcons
///      fonts:
///       - asset: fonts/CutsomIcons.ttf
///
/// 
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
///
import 'package:flutter/widgets.dart';

class CutsomIcons {
  CutsomIcons._();

  static const _kFontFam = 'CutsomIcons';

  static const IconData album = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData genre = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData microphone = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData songs = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData chevron_up = IconData(0xe873, fontFamily: _kFontFam);
  static const IconData chevron_down = IconData(0xe874, fontFamily: _kFontFam);
}
